### ISSUE TITLE
ERROR -Altay 3.0.6

### ISSUE THREAD

**Issue by raidksh** [xXNiceYT/Dino#1]
CRITICAL > dino에서 명령어 'dino Dino' 실행 중 처리되지 않은 예외가 발생했습니다: Call to undefined function Dino\imagecreatefrompng()
18:36:32 CRITICAL > Error: "Call to undefined function Dino\imagecreatefrompng()" (EXCEPTION) in "Dino-master/src/Dino/Main" at line 53
18:36:32 DEBUG > #0 Dino-master/src/Dino/Main(32): Dino\Main->SetSkin(pocketmine\Player object, string Dino, string .png, string dino)
18:36:32 DEBUG > #1 src/pocketmine/command/PluginCommand(58): Dino\Main->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string dino, array Array())
18:36:32 DEBUG > #2 src/pocketmine/command/SimpleCommandMap(283): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string dino, array Array())
18:36:32 DEBUG > #3 src/pocketmine/Server(2070): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string dino Dino)
18:36:32 DEBUG > #4 src/pocketmine/Player(3097): pocketmine\Server->dispatchCommand(pocketmine\Player object, string dino Dino)
18:36:32 DEBUG > #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(267): pocketmine\Player->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
18:36:32 DEBUG > #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
18:36:32 DEBUG > #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(101): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
18:36:32 DEBUG > #8 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
18:36:32 DEBUG > #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(101): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
18:36:32 DEBUG > #10 src/pocketmine/Player(3177): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
18:36:32 DEBUG > #11 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
18:36:32 DEBUG > #12 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 58.121.136.40 52109, raklib\protocol\EncapsulatedPacket object, integer 0)
18:36:32 DEBUG > #13 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
18:36:32 DEBUG > #14 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
18:36:32 DEBUG > #15 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
18:36:32 DEBUG > #16 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
18:36:32 DEBUG > #17 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
18:36:32 DEBUG > #18 src/pocketmine/Server(2323): pocketmine\snooze\SleeperHandler->sleepUntil(double 1534755992.3885)
18:36:32 DEBUG > #19 src/pocketmine/Server(2233): pocketmine\Server->tickProcessor()
18:36:32 DEBUG > #20 src/pocketmine/Server(1794): pocketmine\Server->start()
18:36:32 DEBUG > #21 src/pocketmine/PocketMine(241): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\ghkst\Desktop\Altay-master\, string C:\Users\ghkst\Desktop\Altay-master\plugins\)
18:36:32 DEBUG > #22 C:/Users/ghkst/Desktop/Altay-master/Altay.phar(1): require_once(string phar://C:/Users/ghkst/Desktop/Altay-master/Altay.phar/src/pocketmine/PocketMine.php)

**Comment by xXNiceYT** [comment]
You need enable imagecreatefrompng
