### ISSUE TITLE
PlayerSkin + Geometry.json

### ISSUE THREAD

**Issue by Aroma-Dev** [xXNiceYT/Dino#2]
you can write a plugin that combines player skin and geometry.json so that you can see the player skin but also the geometry.json part.

**===>** _Merge the Skin with the geometry.json_ **<===**

**Comment by xXNiceYT** [comment]
Wat u mean

**Comment by Aroma-Dev** [comment]
=> Merge a Skin(custom Geometry) with the Player Skin
